baseURL = 'https://example.com'
languageCode = 'en-us'
title = 'Vonge'
theme = 'vonge-hugo'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
hasCJKLanguage = true

[pagination]
	pagerSize = 6

[taxonomies]
	tag = 'tags'

[languages]
	[languages.en]
		languageCode = 'en-us'
		languageName = 'English'
		weight = 1
		contentDir = 'content/en'
	[languages.zh-cn]
		languageCode = 'zh-cn'
		languageName = '简体中文'
		weight = 2
		contentDir = 'content/zh-cn'
